blank_issues_enabled: false
contact_links:
  - name: 📧 Security Contact
    url: mailto:ritaban06@gmail.com
    about: For critical security vulnerabilities, please contact us privately
  - name: 📖 Documentation
    url: https://github.com/ritaban06/ignite-new#readme
    about: Check the README and documentation for setup guides and troubleshooting
