name: Build and Release TWA APK (Release)

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Set up Node + pnpm
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      # Setup Bubblewrap CLI
      - name: Install Bubblewrap locally
        run: |
          cd client
          pnpm add @bubblewrap/cli

      # Install Android SDK
      - name: Install Android SDK packages
        run: |
          run: |
          mkdir -p $HOME/Android/Sdk
          curl -s https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/Android/Sdk
          rm cmdline-tools.zip
          mv $HOME/Android/Sdk/cmdline-tools $HOME/Android/Sdk/cmdline-tools-$(date +%Y%m%d)
          echo "y" | $HOME/Android/Sdk/cmdline-tools-$(date +%Y%m%d)/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --licenses
          $HOME/Android/Sdk/cmdline-tools-$(date +%Y%m%d)/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Restore keystore from GitHub secrets
      - name: Restore keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android.keystore

      # Initialize Bubblewrap from website manifest
      - name: Initialize TWA
        run: |
          npx bubblewrap init --manifest=${{ secrets.WEBSITE_MANIFEST_URL }} --no-interactive

      # Build Release APK
      - name: Build Release APK
        run: |
          npx bubblewrap build --release \
            --keystore-path ./android.keystore \
            --keystore-alias ${{ secrets.KEY_ALIAS }} \
            --keystore-pass ${{ secrets.KEYSTORE_PASS }} \
            --key-pass ${{ secrets.KEY_PASS }}

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release-${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload APK to the Release
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: v1.0.${{ github.run_number }}
          files: ./app-release-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
